server:
  port: 9001

logging:
  level:
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server:9000
