server:
  port: 8081

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

security:
  jwt:
    public-key: classpath:public-key.txt

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true