server:
  port: 8081

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "http://localhost:8080/.well-known/jwks.json"

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

security:
  jwt:
    public-key: classpath:public-key.txt

